[global]
ioengine=sync
direct=1
iodepth=1
thread
size=3G
numjobs=64
group_reporting
time_based

[3G_4K_64job_randwrite]
directory=/vepfsE-test/zl/fio/xxx/dir1/dir2/dir3/dir4/dir5/dir6/dir7/3G_4K_64numjobs_randwrite
bs=4K
rw=randwrite
runtime=300
ramp_time=30

[3G_4K_64job_randread]
stonewall
directory=/vepfsE-test/zl/fio/xxx/dir1/dir2/dir3/dir4/dir5/dir6/dir7/3Gfile_4Kio_64numjobs_randread_test
bs=4K
rw=randread
runtime=300
ramp_time=30

[3G_4K_64job_read8write2]
stonewall
directory=/vepfsE-test/zl/fio/xxx/dir1/dir2/dir3/dir4/dir5/dir6/dir7/3Gfile_4Kio_64numjobs_randread_test
bs=4K
rw=randrw
rwmixread=80
runtime=300
ramp_time=30
